// Generated by https://quicktype.io

export interface Estatus {
    id:             number;
    desc:           string;
    tipo:           string;
    siguiente:      number;
    siguienteError: number;
}
