export interface UsuarioCompleto {
    address?: string,
    birthday?: string,
    commune?: string,
    documentCountry?: string,
    documentNumber?: string,
    documentType?: string,
    dv?: string,
    email?: string,
    firstName?: string,
    id: string,
    lastLogin?: string,
    lastName?: string,
    name?: string,
    patent?: string,
    phoneNumber?: string,
    rol: string,
    secondLastName?: string,
    user: string,
    vehicleData?: string,
}